server:
  port: 8081
  servlet:
    context-path: /

spring:
  session:
    store-type: none
  datasource:
    name: lts-executor
    url: jdbc:mysql://localhost:3306/lts-job?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
#    password: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

lts:
  server:
    role: executor
    executor:
      adminUrls: http://localhost:8080
      handler:
        name: test
        host: localhost:8081

lts.job.executor.dir: E:/zhangyue/Its-job/tmp/lts-executor/logs