server:
  port: 8080
  servlet:
    context-path: /

spring:
  session:
    store-type: none
  #  http.converters.preferred-json-mapper: gson
  datasource:
    name: lts-console
    url: jdbc:mysql://localhost:3306/lts-job?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

lts:
  server:
    role: master
    # local or zk
    naming: local
    host: localhost:8080
    handler: test
  alerter:
    phone:
      url: http://192.168.7.175:8080
      default-list: 18710072485
  job:
    console:
      security.ignore.urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/console/auth/login,/handler/**
    thread:
      pools:
        executors:
          - thread-name-prefix: SubmitFlowTask
            corePoolSize:  5
            maxPoolSize: 10
            keepAliveSeconds: 60
            queueCapacity: 1000
            wait-for-tasks-to-complete-on-shutdown: true
            await-termination-seconds: 60

zookeeper:
  server: localhost:2181
  sessionTimeoutMs: 6000
  connectionTimeoutMs: 6000
  maxRetries: 3
  baseSleepTimeMs: 1000