server:
  port: 8080
  servlet:
    context-path: /
  ompression:
    enabled: false
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript
    min-response-size: 2048

  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    port-header: X-Forwarded-Port
  use-forward-headers: true

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  session:
    store-type: none
  #  http.converters.preferred-json-mapper: gson
  datasource:
    name: lts-console
    url: jdbc:mysql://localhost:3306/lts-job?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

lts:
  server:
    role: master
    # local or zk
    naming: local
    #当naming=zk时使用
    host: localhost:8080
    #当role=executor时使用
  alerter:
    phone:
      url: http://localhost:8090
      default-list: 1234567890
  job:
    console:
      security.ignore.urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/console/auth/login,/handler/**
    thread:
      pools:
        executors:
          - thread-name-prefix: SubmitFlowTask
            corePoolSize:  5
            maxPoolSize: 10
            keepAliveSeconds: 60
            queueCapacity: 1000
            wait-for-tasks-to-complete-on-shutdown: true
            await-termination-seconds: 60

# 当 lts.server.naming=zk 时需要配置
zookeeper:
  server: localhost:2181
  sessionTimeoutMs: 6000
  connectionTimeoutMs: 6000
  maxRetries: 3
  baseSleepTimeMs: 1000

# quartz 定时任务配置
lts.quartz.config:
  org.quartz.scheduler.instanceId: AUTO
  org.quartz.scheduler.instanceName: FLOW_TASK_SCHEDULER
  org.quartz.threadPool.threadCount: 10
  org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
  org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
  org.quartz.jobStore.tablePrefix: QRTZ_
  #集群模式，如果是多master模式需要设置为true
  org.quartz.jobStore.isClustered: false
  org.quartz.jobStore.misfireThreshold: 25000

