server:
  port: 8080
  servlet:
    context-path: /

spring:
  session:
    store-type: none
  #  http.converters.preferred-json-mapper: gson
  datasource:
    name: lts-console
    url: jdbc:mysql://localhost:3306/lts-job
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

lts:
  server:
    role: admin
  alerter:
    phone:
      url: http://192.168.7.175:8080/notify/sms/send_warn_sms
      default-list: 18710072485
  job:
    console:
      security.ignore.urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/console/auth/login,/handler/**
    thread:
      pools:
        executors:
          ## 任务提交线程池
          - thread-name-prefix: SubmitFlowTask
            corePoolSize:  5
            maxPoolSize: 10
            keepAliveSeconds: 60
            queueCapacity: 1000
            wait-for-tasks-to-complete-on-shutdown: true
            await-termination-seconds: 60
