server:
  port: 8081
  servlet:
    context-path: /
spring:
  session:
    store-type: none
  datasource:
    name: lts-executor
    url: jdbc:mysql://localhost:3306/lts-job?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
#    password: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

lts:
  server:
    role: executor
    executor:
      adminUrl: http://localhost:8080
      handler:
        name: test
        host: localhost:8081
  job:
    executor.dir: /tmp/lts-executor/logs
    thread:
      pools:
        executors:
          ## Executor回调Master接口线程池
          - thread-name-prefix: MasterCallback
            corePoolSize:  5
            maxPoolSize: 10
            keepAliveSeconds: 60
            queueCapacity: 1000
            wait-for-tasks-to-complete-on-shutdown: true
            await-termination-seconds: 60
            ## executor任务执行线程池
          - thread-name-prefix: ExecutorTaskPool
            corePoolSize:  5
            maxPoolSize: 10
            keepAliveSeconds: 60
            queueCapacity: 1000
            wait-for-tasks-to-complete-on-shutdown: true
            await-termination-seconds: 60