server:
  port: 8081
  servlet:
    context-path: /
spring:
  session:
    store-type: none
  datasource:
    name: lts-executor
    url: jdbc:mysql://localhost:3306/lts-job?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
#    password: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

lts:
  server:
    role: executor
    naming: local
    host: localhost:8081
    handler: test
    executor:
      execute-root: /tmp/lts-executor/logs
      adminUrl: localhost:8080
      handler:
        name: test
        host: localhost:8081
      execute-env:
        CheckInputContentScript: /data/www/lts-job/import-data/CheckFileContent.sh
        HaoopConfigDir: /data/www/lts-job/lts-executor/config/hadoop-config
  job:
    thread:
      pools:
        executors:
          - thread-name-prefix: MasterCallback
            corePoolSize:  5
            maxPoolSize: 10
            keepAliveSeconds: 60
            queueCapacity: 1000
            wait-for-tasks-to-complete-on-shutdown: true
            await-termination-seconds: 60
          - thread-name-prefix: ExecutorTaskPool
            corePoolSize:  5
            maxPoolSize: 10
            keepAliveSeconds: 60
            queueCapacity: 1000
            wait-for-tasks-to-complete-on-shutdown: true
            await-termination-seconds: 60