server:
  port: 9091
  servlet:
    context-path: /
spring:
  session:
    store-type: none
  datasource:
    name: lts-executor
    url: jdbc:mysql://10.100.40.189:3326/lts_job?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: lts_job
    #    password: root
    password: nZfbMTvcZkzALqTF
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

lts:
  server:
    role: executor
    executor:
      execute-root: /data/www/lts-job/lts-executor-import/execute
      adminUrl: http://10.100.102.23:9090
      handler:
        name: ImportData
        host: 10.100.102.23:9091
      execute-env:
        CheckInputContentScript: /data/www/lts-job/lts-executor-import/conf/CheckFileContent.sh
        HaoopConfigDir: /data/www/lts-job/lts-executor-import/conf/hadoop-config
  job:
    thread:
      pools:
        executors:
          ## Executor回调Master接口线程池
          - thread-name-prefix: MasterCallback
            corePoolSize:  5
            maxPoolSize: 10
            keepAliveSeconds: 60
            queueCapacity: 1000
            wait-for-tasks-to-complete-on-shutdown: true
            await-termination-seconds: 60
            ## executor任务执行线程池
          - thread-name-prefix: ExecutorTaskPool
            corePoolSize:  5
            maxPoolSize: 10
            keepAliveSeconds: 60
            queueCapacity: 1000
            wait-for-tasks-to-complete-on-shutdown: true
            await-termination-seconds: 60
